### ISSUE TITLE
Use environment variables to provide credentials

### ISSUE THREAD

**Issue by wojtekwalczak** [aliyun/Resource-Orchestration-Service-Cloud-Development-Kit#13]
Hi,

I would like to use `ros-cdk` in a CI/CD pipeline, but currently the only way to provide credentials is to use interactive options like `ros-cdk config` or `ros-cdk load-config`.

The most convenient way would be if `ros-cdk` could pick up the credentials from environment variables like `ALICLOUD_ACCESS_KEY`, `ALICLOUD_SECRET_KEY` and `ALICLOUD_REGION`.

**Comment by Ehzyo** [comment]
ros-cdk-cli 1.0.12 is release. 
If you want to use ros-cdk in a CI/CD pipeline, try `ros-cdk config-set` instead.

We have received suggestions and will support this feature in the future.

**Comment by Ehzyo** [comment]
ros-cdk-cli 1.0.12 is release.
If you want to use ros-cdk in a CI/CD pipeline, try ros-cdk config-set instead.

We have received suggestions and will support this feature in the future.
