### ISSUE TITLE
Provide synchronous deploy

### ISSUE THREAD

**Issue by wojtekwalczak** [aliyun/Resource-Orchestration-Service-Cloud-Development-Kit#14]
Hi,

when deploying stacks with `ros-cdk deploy`, the deployment process is asynchronous, so we need to develop some custom ways of checking what's the status of the deployment.

It would be much more useful if `ros-cdk deploy` would work in a synchronous manner, which is more natural for transactional nature of the deployment process.

If that's not possible, could you suggest the best way to programmatically monitor the deployment status?

**Comment by Ehzyo** [comment]
We have received suggestions and will support this feature in the future.

Current solution：
- CLI：
  - Check stack event status via `ros-cdk event`.
  - Check stack status via [aliyun ROS CLI](https://www.alibabacloud.com/help/doc-detail/137400.htm?spm=a2c63.l28256.b99.488.2a7713a3mdJAiG#title-k21-mmh-lrb).
For example: `aliyun ros ListStacks --RegionId <region_id> -StackName.1 <stack_name>`.
- Code：Check stack status via [aliyun ROS SDK](https://www.alibabacloud.com/help/doc-detail/28928.htm?spm=a2c63.p38356.b99.686.39ab23e6fUmM3D)

**Comment by Ehzyo** [comment]
ros-cdk-cli 1.0.15 is released. The progress of resource creation is added.
