### ISSUE TITLE
Provide change log

### ISSUE THREAD

**Issue by wojtekwalczak** [aliyun/Resource-Orchestration-Service-Cloud-Development-Kit#22]
Hi, thank you for letting us know that ros-cdk CLI 1.0.12 has been released. To make it easier for us to track what has been changed in the new versions, could you start providing changes log for new releases? Something similar to [this](https://github.com/aws/aws-cdk/blob/master/CHANGELOG.md) would be great.

**Comment by Ehzyo** [comment]
We have received suggestions and will add release note next time, including change log of ros-cdk CLI 1.0.12.

**Comment by Ehzyo** [comment]
Release note has been added.

https://github.com/aliyun/Resource-Orchestration-Service-Cloud-Development-Kit/blob/master/ReleaseNote.md
