### ISSUE TITLE
Synchronous deployment fails when stack has not changed 

### ISSUE THREAD

**Issue by adam-staros** [aliyun/Resource-Orchestration-Service-Cloud-Development-Kit#31]
Right now `ros-cdk deploy {stack_name} --sync` fails when stack do not contains any new changes since last deployment. 

Error: `fail to sync update stack: NotSupported Update the completely same stack {stack_name} is not supported`

It would be great to add flag like `--skip-if-no-changes` to `ros-cdk deploy --sync` command to handle such situations.

ros-cdk version: 1.0.17

**Comment by Ehzyo** [comment]
ros-cdk 1.0.18 is released, `--skip-if-no-changes` is supported.
`ros-cdk deploy {stack_name} --sync --skip-if-no-changes`
