### ISSUE TITLE
Create ROS stack in given resource group

### ISSUE THREAD

**Issue by piotr-kalanski** [aliyun/Resource-Orchestration-Service-Cloud-Development-Kit#36]
Hi,

Is it possible to select resource group when creating ROS stack using ROS CDK?
I don't see any argument in `ros-cdk deploy` command for this purpose (https://partners-intl.aliyun.com/help/en/doc-detail/204710.html).
I also didn't find any argument in Alibaba Cloud CLI in Create Stack command (https://partners-intl.aliyun.com/help/en/doc-detail/137400.html), but there is parameter `ResourceGroupId` in `CreateStack` API call (https://partners-intl.aliyun.com/help/en/doc-detail/132086.html?spm=a2c63.p38356.0.0.4591177aPoowtR).

What is recommended approach to create stacks in given resource group?
I think it would be good to add dedicate argument in `ros-cdk deploy` to provide resource group id.

**Comment by baichenxu3** [comment]
We have received suggestions, and are considering about this feature.

**Comment by piotr-kalanski** [comment]
Hi,

I was reviewing source code and I think below commit might add feature to provide resource group id:
https://github.com/piotr-kalanski/Resource-Orchestration-Service-Cloud-Development-Kit/commit/2a12deea757ac69e69708dd9fd159fba12cfba0e

**Comment by baichenxu3** [comment]
First of all, thank you for your support and suggestions. We will refer to your submission code, but there are still some related problems to deal with, so we can't merge your submission. At present, we are dealing with this problem, and it is expected to be released this week

**Comment by baichenxu3** [comment]
ros-cdk-core 1.0.20 is released. The issue is fixed. you can set ros-cdk deploy --resource-group-id to use.

**Comment by piotr-kalanski** [comment]
Great :) Thank you very much.
