### ISSUE TITLE
How to use ros-cdk generate-stack-file with an account limited to a resource group

### ISSUE THREAD

**Issue by kucharzyk-sebastian** [aliyun/Resource-Orchestration-Service-Cloud-Development-Kit#40]
Hi,

We've got a production account that's shared between multiple teams. Our team has limited access only to one resource group there. We managed to deploy a stack to the resource group successfully using `ros-cdk`, however, we have problems when using `ros-cdk generate-stack-file`. To be precise, it shows that all stacks are in the `init` state even though they are deployed. When we try to deploy again, we get the following error:
```
fail to sync create stack: StackExists The Stack (my-stack) already exists
```

On the other hand, in our dev account where we have full access not limited to a resource group, the `generate-stack-file` works properly. 

Do you have any suggestions on how we can make it work on both accounts?

**Comment by baichenxu3** [comment]
First of all, I don't understand why you need to use the ros-cdk generate-stack-file command, because the ros-cdk generate-stack-file command is only restoring the user to delete the stack.info.json file. Secondly, if you have multiple accounts and need to manage multiple resources, you can create multiple RAM account , and create and manage resources with different RAM accounts corresponding to different resource groups.

**Comment by kucharzyk-sebastian** [comment]
Hi @baichenxu3, thanks for your reply. We use  `ros-cdk generate-stack-file` command to dynamically generate the stack-file during the deployment processes. We do it to avoid storing the file under version control since it was problematic for our CI/CD workflow.

We have different RAM accounts associated with different resource groups and it works fine. The problem is slightly different, the `ros-cdk generate-stack-file` doesn't work in the account where we have access limited only to a resource group. It says that all stack has the `init` state even though they exist. I think that this might be related to some missing permissions as we don't have this issue in the account where we have a full access.

Would it be possible for you to tell me what RAM actions/permissions does the `ros-cdk generate-stack-file` need?

**Comment by baichenxu3** [comment]
I think you should set the following permissions corresponding to your RAM account and the resource group to be managed to manage resources,
read permissions:
ros:GetStack | ros:ListStacks | ros:ListStackEvents | ros:ListStackResources | ros:GetTemplate
Write permission:
ros:CreateStack|  ros:UpdateStack|  ros:DeleteStack
Please set the corresponding permission policy for the RAM account before use ros-cdk generate-stack-file

**Comment by kucharzyk-sebastian** [comment]
Thanks @baichenxu3, we managed to make it work. We already had these permissions set for the resource group but it was also needed to set them for the global scope of the account. Do you think it might be the issue on the ros-cdk side that permissions to a resource group are not enough?

**Comment by baichenxu3** [comment]
When you only set the above permissions on the resource group, can you use the RAM account to try to call the above API through the [Open API Explorer](https://api.aliyun.com/?spm=5176.cnopenapiexplorer.0.0.253a71a3zrEm7Z&aly_as=VqJJAydwA#/?product=ROS&version=2019-09-10&api=ListStacks&params={}&tab=DOC&lang=PYTHON), such as: ROS: getstack | ROS: liststacks | ROS: liststackeevents | ROS: liststackeresources | ROS: getTemplate | createstack | ROS: updatestack | ROS: deletestack

**Comment by kucharzyk-sebastian** [comment]
I tried with ROS:liststacks and I wasn't able to do when I only had permissions to the resource group.

**Comment by Ehzyo** [comment]
I think there is a missing feature here.
If `ros-cdk list, deploy, list-stacks, event, output, resource, destroy and generate-stack-file` all support `--resource-group-id`, it works.
Because ROS:ListStacks will use default resource group if ResourceGroupId is not passed.

**Comment by kucharzyk-sebastian** [comment]
Hi @Ehzyo, sorry for the late reply, I got occupied by other tasks. Can I share the RequestId with you somewhere using private communication? I'd prefer not to disclose it in a public thread.

**Comment by Ehzyo** [comment]
How about DingTalk. The DingTalk group number is 11783495.

**Comment by kucharzyk-sebastian** [comment]
Unfortunately, we don't have access to DingTalk :(

**Comment by Ehzyo** [comment]
You may mail to us: `ros.cdk.2022@gmail.com`.

**Comment by kucharzyk-sebastian** [comment]
Thanks, @Ehzyo. I've just dropped you a message with the request ID.

**Comment by Ehzyo** [comment]
Thanks, @kucharzyk-sebastian . The issue has been clarified. It is due to the lack of functionality. We will add --resource-group-id option to command `ros-cdk generate-stack-file`.

We will fix this in the next few days.

**Comment by kucharzyk-sebastian** [comment]
Thanks, Ehzyo. that's amazing news!

**Comment by Ehzyo** [comment]
ros-cdk-cli 1.0.23 is released, and the issue is fixed. Try `ros-cdk generate-stack-file --resource-group-id <your resource group id>`.

**Comment by kucharzyk-sebastian** [comment]
It works great now. Thanks, @Ehzyo!
