### ISSUE TITLE
Output exportName has no effect

### ISSUE THREAD

**Issue by kucharzyk-sebastian** [aliyun/Resource-Orchestration-Service-Cloud-Development-Kit#43]
Hi,

I've just tried to define `ros.RosOutput` in one stack and use it in another. It failed when I tried to use `exportName` but it succeeded when I used the `id`.

Here's a failing code:
```typescript
import * as ros from '@alicloud/ros-cdk-core';
import * as oss from '@alicloud/ros-cdk-oss';

export class StackDefiningOutput extends ros.Stack {
  constructor(scope: ros.Construct, id: string, props?: ros.StackProps) {
    super(scope, id, props);
    new ros.RosOutput(this, `my-output-id`, {
      value: 'my-output-value',
      exportName: "my-output-export-name",
    });
  }
}

export class StackUsingOutput extends ros.Stack {
  constructor(scope: ros.Construct, id: string, props?: ros.StackProps) {
    super(scope, id, props);
    const outputName = "my-output-export-name";
    const output = ros.Fn.getStackOutput("StackDefiningOutput", outputName)
    new oss.Bucket(this, "my-output-based-bucket", {
      bucketName: output.toString(),
    })
  }
}
```

And it's enough to change `const outputName = "my-output-export-name"` in line 17 to ` const outputName = "my-output-id"` to make it work. Is this behavior expected? If it is, then what is the purpose of the `exportName` parameter?

**Comment by Ehzyo** [comment]
It is expected.
CDK is based on ROS, and  ROS  does not support export now. exportName is reversed for future expansion.

**Comment by kucharzyk-sebastian** [comment]
All is clear now. Thanks @Ehzyo !
