### ISSUE TITLE
Cannot update stack with resource-group-id 

### ISSUE THREAD

**Issue by kucharzyk-sebastian** [aliyun/Resource-Orchestration-Service-Cloud-Development-Kit#44]
Hi,

We cannot update a stack with a resource group using ros-cdk. Steps to reproduce:

1. Execute `ros-cdk deploy <MASKED> --resource-group-id <MASKED>`
2. Wait for the stack to be successfully created
3. Execute `ros-cdk deploy <MASKED> --resource-group-id <MASKED>` again. The command fails with the error below:
`fail to update stack, cannot support set resource-group-id params to this operation.`

**Comment by baichenxu3** [comment]
CDK is based on ROS, and ROS UpdateStack API does not support update ResourceGroupId now. so, It cannot be supported at present.

**Comment by kucharzyk-sebastian** [comment]
Hi @baichenxu3, thanks for the reply, it's clear now. However, I think people may expect two exactly the same commands to have the same result and the whole operation to be idempotent. Would it be possible to implement it in `ros-cdk` to ignore the `resource-group-id` if the deployment is invoked for an update? I.e.:
```bash
ros-cdk deploy <MASKED> --sync --resource-group-id <MASKED> # Creates a stack in resource group
ros-cdk deploy <MASKED> --sync --resource-group-id <MASKED> # Ignore resource group id and update
```

Otherwise, every client using resource groups would need to write custom code to check it which seems to be harder than including the feature in ros-cdk. What do you think about it?

**Comment by Ehzyo** [comment]
UpdateStack support ResourceGroupId has been arranged for development. The current solution is to use commands such as ros-cdk list to determine the deployment status.

**Comment by kucharzyk-sebastian** [comment]
Thanks, guys. We will work on a workaround on our side and we'll keep our fingers crossed for the feature to appear in ROS in the future ;).

**Comment by Ehzyo** [comment]
UpdateStack supports ResourceGroupId now.
ros-cdk-cli 1.0.24 is released, the validation of --resource-group-id has been removed. 
@kucharzyk-sebastian

**Comment by kucharzyk-sebastian** [comment]
Thanks, @Ehzyo, I can confirm it works well now!
