### ISSUE TITLE
Cannot create API Gateway Custom Domain with SSL certificate

### ISSUE THREAD

**Issue by kucharzyk-sebastian** [aliyun/Resource-Orchestration-Service-Cloud-Development-Kit#48]
Hi,

I'm trying to create ApiGateway CustomDomain using ros-cdk. I have code like the following in my stack:
```typescript
import * as apigateway from "@alicloud/ros-cdk-apigateway";

// ...

    new apigateway.CustomDomain(this, `my-custom-domain`, {
      domainName: `<MASKED>`,
      groupId: "<MASKED>",
      certificateName: "cert-1234567",
    });
```

Unfortunately, it fails with the message below:
```
 StackValidationFailed Property error: : Resources.my-stack-my-custom-domain.Properties.CertificateName: : cert-1234567 is invalid. Its length should be 4-50 characters, and should begin with upper or lower case letter or Chinese. Numbers or "_" are included.
```

I'm wondering if I'm not using it properly or if there's a bug somewhere? The certificate exists in Aliyun Certificate Management System and I'm able to apply it using Aliyun console, but I cannot do it using ros-cdk.

**Comment by Ehzyo** [comment]
This is a limitation of ROS service. We have removed it. Try again.

**Comment by kucharzyk-sebastian** [comment]
Thanks @Ehzyo. It went further and I managed to create the stack but I have two issues now:
1. The certificate wasn't associated with the API Group (screenshot from Aliyun console attached)
2. When I try to update the stack, I still get the error message below. It worked fine for create though.
```
fail to sync update stack: StackValidationFailed cert-1234567 is invalid. Its length should be 4-50 characters, and should begin with upper or lower case letter or Chinese. Numbers or "_" are included.,
```

![image](https://user-images.githubusercontent.com/36233877/164442043-54eff34b-d6c1-45c9-bdcf-713db94b5902.png)

**Comment by Ehzyo** [comment]
Can you provide more information to help us to figure out the issue:
-  StackId for issue 1.
-  RequestId for issue 2.

We already have some doubts and want to confirm further. If it is confirmed, we will fix the issue in ROS Service in next few days.

**Comment by Ehzyo** [comment]
The fix will be published in ROS Service on 4.25.

**Comment by kucharzyk-sebastian** [comment]
Thanks @Ehzyo. I've send the detailes you asked for to ros.cdk.2022@gmail.com. I hope that's OK.

**Comment by Ehzyo** [comment]
Thanks @kucharzyk-sebastian . Based on the information you provide, We confirm it. 
The fix will be published in ROS Service on 4.25.

**Comment by Ehzyo** [comment]
Hi @kucharzyk-sebastian . The issues have been fixed in ROS Service. Please try again.

**Comment by kucharzyk-sebastian** [comment]
Hi @Ehzyo. It went further this time. Unfortunately, it failed in ROS with the error below but I'm not sure if that's connected with `ros-cdk` or something else. It works fine without setting `certificateName` attribute though.
```
Resource CREATE failed: ResponseException: resources.my-stack: There is not available Zone for the user. Code: [InternalError](https://error-center.aliyun.com/status/search?Keyword=InternalError).
```

**Comment by Ehzyo** [comment]
Hi @kucharzyk-sebastian. The error comes from ApiGateway. We are contacting them to help investigate.

**Comment by Ehzyo** [comment]
@kucharzyk-sebastian 

The error comes from API ApiGateway:SetDomainCertificate. The actual error message is "The CertificateBody is mandatory for this action". ApiGateway will optimize the error message.

How to solve the problem? Set certificateBody and certificatePrivateKey.
If you have already passed the certificate, CertificateBody and CertificatePrivateKey can be left blank. Otherwise, they are required.

**Comment by kucharzyk-sebastian** [comment]
Hmm, I'm not sure if I understand how to solve it. I have the certificate already uploaded to Aliyun. When I Go to the API Gateway command, press `Select certificate` and choose the certificate, it works fine:
1. ![image](https://user-images.githubusercontent.com/36233877/165274738-e252d48a-7d67-4f87-ac12-6031452f2197.png)
2. ![image](https://user-images.githubusercontent.com/36233877/165277541-0bb306ec-b599-4740-a3d7-1ea908dabed0.png)
3. ![image](https://user-images.githubusercontent.com/36233877/165276239-32e4f468-a751-4576-ae02-219ca2d84568.png)

However, it still throws the internal error when we deploy from the ros-cdk using only `certificateName`. Do we need to pass the body and the private key even though the certificate exists in the Aliyun cloud? I would prefer to avoid passing these since the certificate is already in the cloud. Do you know if it should be possible that way?

**Comment by Ehzyo** [comment]
@kucharzyk-sebastian 
We asked the ApiGateway developers and they said that the console will help users get the certificate content automatically, but the Api needs to fill it out by itself.

We can also provide such a function through the ROS Service. But the time will be slightly later, around May 5th or 6th.

**Comment by kucharzyk-sebastian** [comment]
Oh, it would be great if you could make it possible to pass the `certificateName` only with ROS. It would simplify a lot because people wouldn't need to write additional code to avoid storing private keys in arepository 😃.

**Comment by Ehzyo** [comment]
For some other reason, sorry to postpone the release date to May 9.

**Comment by Ehzyo** [comment]
@kucharzyk-sebastian 
It is published in ROS Service.
This function requires authorization to the following API:
```
yundun-cert:DescribeUserCertificateDetail
yundun-cert:DescribeUserCertificateList
```
If there is no authorization, the error is the same as before.

**Comment by kucharzyk-sebastian** [comment]
Thanks, @Ehzyo. It works great now!
