### ISSUE TITLE
Read timeout during synchronous stack deployment

### ISSUE THREAD

**Issue by kucharzyk-sebastian** [aliyun/Resource-Orchestration-Service-Cloud-Development-Kit#49]
Hi,

We're using `ros-cdk deploy my-stack --sync --skip-if-no-changes` command to deploy our stacks. As the stacks grew, we started observing the `fail to sync update stack: undefined ReadTimeout(15000)` error below during some of the updates of the stacks. Right now, it happens almost every time. Is there a way to override this timeout to make it longer or fix this issue in some other way?

**Comment by Ehzyo** [comment]
@kucharzyk-sebastian 

We will increase the request timeout in next cli release (as soon as today). It will solve your problem.

We will handle network exception in future release.

**Comment by Ehzyo** [comment]
@kucharzyk-sebastian 

`ros-cdk-cli 1.0.25` is released. The issue has been fixed.

**Comment by kucharzyk-sebastian** [comment]
Thanks, everything went back to normal today :)
