### ISSUE TITLE
secondaryZoneId parameter missing in ros-cdk-redis

### ISSUE THREAD

**Issue by oort7** [aliyun/Resource-Orchestration-Service-Cloud-Development-Kit#52]
Hi,

When creating a Redis instance, ApsaraDB For Redis API provides possibility to pass `secondaryZoneId`: https://partners-intl.aliyun.com/help/en/apsaradb-for-redis/latest/createinstance

Do you plan to add this parameter to ros-cdk? Currently only `zoneId` is supported.

**Comment by Ehzyo** [comment]
We have arranged development, and ros-cdk will release a new version in 1~2 weeks.

**Comment by Ehzyo** [comment]
@oort7 
`@alicloud/ros-cdk-redis` 1.0.6 is released, and secondaryZoneId is supported.

**Comment by oort7** [comment]
@Ehzyo Thank you very much!
