### ISSUE TITLE
Create Aliyun Logservice Metricstore with ros-cdk?

### ISSUE THREAD

**Issue by kucharzyk-sebastian** [aliyun/Resource-Orchestration-Service-Cloud-Development-Kit#54]
Hi,

We're using a Metricstore from Aliyun Logservice and we create it using a [guide on the official website](https://partners-intl.aliyun.com/help/en/log-service/latest/manage-metricstores). We want to automate the process with `ros-cdk` but I cannot find appropriate constructs. Could you advise if creating a metricstore with ros-cdk is possible?

**Comment by Ehzyo** [comment]
@kucharzyk-sebastian 
Metricstore is supported in `@alicloud/ros-cdk-sls` 1.0.6.

**Comment by kucharzyk-sebastian** [comment]
Thanks, @Ehzyo. I must've had an older version. I'll use a newer one!
