### ISSUE TITLE
SLS Alert create fails in Hangzhou region

### ISSUE THREAD

**Issue by sq2gxo** [aliyun/Resource-Orchestration-Service-Cloud-Development-Kit#57]
We have an LogService MetricStore Alert resource https://www.alibabacloud.com/help/en/resource-orchestration-service/latest/aliyun-sls-alert defined in our stack.
Deployment works fine in our dev environment in EU-Germany(Frankfurt) region. But when we try to deploy exactly the same ROS stack in Hangzhou we have error:
status: UPDATE_FAILED
StatusReason: Resource UPDATE failed: ResponseException: resources.prelive-vs-webrtc-service-china-stateful-coturn-instances-alert: The Project does not exist : prelive-vs-webrtc-service-china-stateful-logserviceproject Code: ProjectNotExist RequestId: 6298866A9A89BAF33B94B876

The project exits. I'm able to create same alert in Hangzhou via API (using Python client) but from ros-cdk it fails

ros-cdk version 1.0.6

**Comment by Ehzyo** [comment]
We will fix the issue in next publish of ROS service.

**Comment by Ehzyo** [comment]
The issue has been fixed. Please try again.

**Comment by sq2gxo** [comment]
It is working now - thank you :)
