### ISSUE TITLE
Create a RAM role containing policy without specifying version

### ISSUE THREAD

**Issue by kucharzyk-sebastian** [aliyun/Resource-Orchestration-Service-Cloud-Development-Kit#58]
Hi,

According to [the documentation](https://www.alibabacloud.com/help/en/resource-orchestration-service/latest/aliyun-ram-role#section-anq-zb4-59j) of ROS, `version` attribute in the `PolicyDocument` is not required. Unfortunately, when I try to create a RAM role containing policy without the version (code below) I get the error `Resource CREATE failed: ResponseException: resources.my-test-role: The policy document is invalid. apsara::AnyCast: can't cast from v to Ss Code: MalformedPolicyDocument`.

```typescript
import * as ros from '@alicloud/ros-cdk-core';
import * as ram from '@alicloud/ros-cdk-ram';

export class PocRosCdkPolicyStack extends ros.Stack {
  constructor(scope: ros.Construct, id: string, props?: ros.StackProps) {
    super(scope, id, props);
    new ram.Role(this, "my-test-role", {
      roleName: "my-test-role",
      assumeRolePolicyDocument: {
        version: "1",
        statement: [
          {
            action: "sts:AssumeRole",
            effect: "ALLOW",
            principal: {
              service: ["ecs.aliyuncs.com"],
            },
          },
        ],
      },
      policies: [
        {
          policyName: `${id}-my-policy`,
          policyDocument: {
            statement: [
              {
                effect: "ALLOW",
                action: ["log:PostLogStoreLogs"],
                resource: [`acs:log:*:*:project/myproject/logstore/mystore`],
              },
            ],
          },
        },
      ],
    });
  }
}
```

When I add the `version` to the `policyDocument` everything works well. It seems that there's a discrepancy between the documentation and the `ros-cdk` behavior. Is it possible to create a Ram Role containing policy without a version?

**Comment by baichenxu3** [comment]
This is the problem of our service, we will fix it later. It is necessary to create a Ram Role containing policy without a version and Please to set the value of effect to "Allow"  instead of  "ALLOW".

**Comment by kucharzyk-sebastian** [comment]
Thanks!
