### ISSUE TITLE
API Gateway Deployment description is required

### ISSUE THREAD

**Issue by kucharzyk-sebastian** [aliyun/Resource-Orchestration-Service-Cloud-Development-Kit#61]
Hi,

I've just tried to create an API Gateway Deployment but it failed with the error message:
```
Resource CREATE failed: ResponseException: resources.PocCanaryApiStackApiDeployment: Description is mandatory for this action. Code: [MissingDescription](https://error-center.aliyun.com/status/search?Keyword=MissingDescription)
```
I believe that the description parameter should be marked as required [here](https://github.com/aliyun/Resource-Orchestration-Service-Cloud-Development-Kit/blob/master/multiple-languages/js/alicloud-ros-cdk-apigateway-1.0.8/lib/deployment.d.ts#L23). Right now, it's optional.

**Comment by Ehzyo** [comment]
The issue will be fixed in next ROS publish. If description is not specified, a default value will be used.

**Comment by Ehzyo** [comment]
@kucharzyk-sebastian 
The issue has been fixed. The description parameter is still optional.  If it is not specified, a default value will be used.
