### ISSUE TITLE
Use Config settings as defaults when resetting Config values

### ISSUE THREAD

**Issue by QYongHao** [aliyun/Resource-Orchestration-Service-Cloud-Development-Kit#66]
Allow users to just press enter when submitting one of these values to skip resetting that particular value. This allows them to only enter a value they want to replace instead of having to enter all the values each time.

https://github.com/aliyun/Resource-Orchestration-Service-Cloud-Development-Kit/blob/9334da41f32c49e0c47647cfeec39df07b899576/packages/ros-cdk-cli/lib/cdk-toolkit.ts#L285

**Comment by baichenxu3** [comment]
ros-cdk-cli 1.0.35 is released. The feature is supported.
```shell
ros-cdk config
Endpoint(optional, [https://ros.aliyuncs.com]):
RegionId(optional, [cn-beijing]):

[1] AK
[2] StsToken
[3] RamRoleArn
[4] EcsRamRole
[0] CANCEL

Authenticate mode [AK] [1...4 / 0]: 1
AccessKeyId [LTAI4G5b********wxz3BvSq]:
AccessKeySecret [pmZPATWYiO**********UCIyhvpCYO]:

 ✅ Your cdk configuration has been saved successfully!
```

**Comment by QYongHao** [comment]
Thanks for this! It's very convenient to have.
