### ISSUE TITLE
Receiving "Cannot read properties of undefined (reading 'RequestId')" Error while running "ros-cdk deploy"

### ISSUE THREAD

**Issue by QYongHao** [aliyun/Resource-Orchestration-Service-Cloud-Development-Kit#68]
Here is the full error from running: **ros-cdk deploy --detail-log**

```
create stack error info is {
  name: 'SyntaxError',
  message: "Unexpected '<'",
  at: 3,
  text: '\r\n' +
    '<a id="a-link" href="https://g.alicdn.com/sd/punish/waf_block.html?wh_ttid=pc&uuid=c0c98bb47896567f4a64188d14e71a1e&origin=https%3A%2F%2Fros.aliyuncs.com%2F"></a>\r\n' +
    '<script>\r\n' +
    '  document.getElementById("a-link").click();\r\n' +
    '\r\n' +
    '  window._config_ = {\r\n' +
    '    "action": "block",\r\n' +
    '    "url": "https://g.alicdn.com/sd/punish/block_h5.html?wh_ttid=pc&uuid=c0c98bb47896567f4a64188d14e71a1e&origin=https%3A%2F%2Fros.aliyuncs.com%2F"\r\n' +
    '  };\r\n' +
    '</script>\r\n' +
    '<!--rgv587_flag:sm-->'
}
create stack error info is TypeError: Cannot read properties of undefined (reading 'RequestId')
    at CdkToolkit.rosCreateStack (/root/.nvm/versions/node/v18.12.1/lib/node_modules/@alicloud/ros-cdk-cli/lib/cdk-toolkit.js:1633:43)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async CdkToolkit.deploy (/root/.nvm/versions/node/v18.12.1/lib/node_modules/@alicloud/ros-cdk-cli/lib/cdk-toolkit.js:639:21)
    at async main (/root/.nvm/versions/node/v18.12.1/lib/node_modules/@alicloud/ros-cdk-cli/bin/cdk.js:304:17)
    at async initCommandLine (/root/.nvm/versions/node/v18.12.1/lib/node_modules/@alicloud/ros-cdk-cli/bin/cdk.js:243:25)
Cannot read properties of undefined (reading 'RequestId')
```

The error doesn't seem to be coming from the CLI, but it would be nice to get a more informative error for what's happening here.

For some context, started getting this error after I deleted the stack that was managed by ros-cdk through the ROS console. I am not sure if that's what caused this, but some more guidance on what is going wrong here would be helpful (and how to resolve this issue).

**Comment by baichenxu3** [comment]
Whether you can currently run the command correctly ros-cdk synth -j  view your stack template

**Comment by QYongHao** [comment]
The output works. I can even create a stack with it through the ROS console. Only issue is running "ros-cdk deploy".

**Comment by baichenxu3** [comment]
Can you tell us the detailed operation process, our side needs to try to reproduce locally

**Comment by QYongHao** [comment]
There's not much to detail. Just running ros-cdk deploy causes the error to occur. Are there any ways to track this issue down with the error message shown?

This looks like a pretty interesting error. Not sure where this is coming from, but it's very strange that HTML is involved in what should be a simple CLI request?

{
  name: 'SyntaxError',
  message: "Unexpected '<'",
  at: 3,
  text: '\r\n' +
    '<a id="a-link" href="https://g.alicdn.com/sd/punish/waf_block.html?wh_ttid=pc&uuid=c0c98bb47896567f4a64188d14e71a1e&origin=https%3A%2F%2Fros.aliyuncs.com%2F"></a>\r\n' +
    '<script>\r\n' +
    '  document.getElementById("a-link").click();\r\n' +
    '\r\n' +
    '  window._config_ = {\r\n' +
    '    "action": "block",\r\n' +
    '    "url": "https://g.alicdn.com/sd/punish/block_h5.html?wh_ttid=pc&uuid=c0c98bb47896567f4a64188d14e71a1e&origin=https%3A%2F%2Fros.aliyuncs.com%2F"\r\n' +
    '  };\r\n' +
    '</script>\r\n' +
    ''
}

**Comment by EhzyoWang** [comment]
The request was blocked by a security system, we are contacting them for help.

We've provided all the error information we could. This can only be done manually at present.

**Comment by QYongHao** [comment]
Thank you, I'll wait for an update on what to do. Hopefully I can use **ros-cdk deploy** again. Right now, I've gotten the workaround of using aliyun-cli to deploy my stacks instead of ros-cdk.

**Comment by EhzyoWang** [comment]
Could you provide the StackId of the successful deployment after switching to aliyun-cli? We will try to figure out what triggers the security interception.

**Comment by QYongHao** [comment]
I already deleted the stack. But I managed to create a stack with the default App template using ros-cdk deploy: df207b8f-aa29-4031-9699-c1c3db88cc6b

I even used the same account.config.json

**Comment by QYongHao** [comment]
Found the problematic part of the code:
```
        const dbInstanceClass: ros.RosParameter = new ros.RosParameter(this, 'DBInstanceClass', {
            type: ros.RosParameterType.STRING,
            description: 'Select the instance specification based on the type of database engine and the available area support',
            label: 'RDS',
            defaultValue: 'rds.mysql.t1.small',
            allowedValues: [
                "rds.mysql.t1.small",
                "rds.mysql.s1.small",
                "rds.mysql.s2.large",
                "rds.mysql.s2.xlarge",
                "rds.mysql.s3.large",
                "rds.mysql.m1.medium",
                "rds.mysql.c1.large",
                "rds.mysql.c1.xlarge",
                "rds.mysql.c2.xlarge",
                "rds.mysql.c2.xlp2",
                "rds.mysql.c2.2xlarge",
                "rds.mysql.st.d13"
            ]
        });
...
        new rds.DBInstance(this, 'Database', {
            dbInstanceClass: dbInstanceClass,
            zoneId: zoneId,
            dbMappings: [
                {
                    dbName: dbName,
                    characterSetName: 'utf8'
                }
            ],
            dbInstanceDescription: "Database",
            dbInstanceStorage: dbInstanceStorage,
            vSwitchId: vSwitch.attrVSwitchId,
            engine: ros.Fn.select(0, ros.Fn.split('-', dbInstanceEngineAndVersion.valueAsString)),
            masterUserPassword: dbPassword,
            masterUsername: dbUser,
            vpcId: vpc.attrVpcId,
            engineVersion: ros.Fn.select(1, ros.Fn.split('-', dbInstanceEngineAndVersion.valueAsString)),
            securityIpList: '0.0.0.0/0'
        });
````

Needed to comment out both of these sections to get ros-cdk deploy working. Commenting out just the RDS.Instance still gives the same error.

**Comment by EhzyoWang** [comment]
The template or parameters of the stack may contain some content that is misjudged by the security system. In most cases, ros-cdk can be used normally, but for requests containing misjudged content, the above errors may occur.

We will try to avoid this problem in the next version.

Now we are looking for someone from the security system to help to remove misjudgment.

**Comment by EhzyoWang** [comment]
Misjudgments is being eliminated. It takes about 2 hours. You can try it again 2 hours later.

And we will try to avoid this problem in the next version.（@alicloud/ros-cdk-cli current 1.0.35, next 1.0.36）

**Comment by QYongHao** [comment]
Thanks! This issue is resolved now.

**Comment by EhzyoWang** [comment]
@QYongHao
@alicloud/ros-cdk-cli 1.0.36 is released. If the issue occurs again, you may try the new version.
